import {
  generateFidelityFixture,
  sqlCapabilityFixtures,
  sqlExportFixtures,
} from "@er-diagram/test-fixtures";
import { describe, expect, it } from "vitest";
import {
  convertDbmlToSqlExport,
  convertSqlImport,
  parseDbmlV2,
  sha256Utf8,
  SQL_EXPORT_REPORT_VERSION,
  SQL_EXPORT_SEMANTICS_VERSION,
} from "../src/index.js";
import { verifyExportableSchemaGraphs } from "../src/sql-export-semantics.js";
import { analyzeSqlSource } from "../src/sql-source-analyzer.js";

const EXPORT_HEADER = `-- Generated by DBML·SQL ERD Studio as empty-schema create DDL.
-- This is not a migration. Review before applying to an existing database.`;

describe("same-dialect SQL export", () => {
  it("matches the versioned SQL export corpus and its golden hashes", async () => {
    for (const fixture of sqlExportFixtures) {
      const result = await convertDbmlToSqlExport({
        primaryDialect: fixture.dialect,
        targetDialect: fixture.dialect,
        source: fixture.source,
        filepath: `/fixtures/${fixture.id}.dbml`,
        hasPersistedLayout: fixture.hasPersistedLayout,
      });

      expect(result.report.reportVersion, fixture.id).toBe(SQL_EXPORT_REPORT_VERSION);
      expect(result.report.exportSemanticsVersion, fixture.id).toBe(SQL_EXPORT_SEMANTICS_VERSION);
      expect(result.report.overallStatus, fixture.id).toBe(fixture.expectedOverallStatus);
      expect(result.report.sourceHash, fixture.id).toBe(fixture.sourceHash);
      expect(result.report.parserInputHash, fixture.id).toBe(fixture.sourceHash);
      expect(
        result.report.entries.map(({ code }) => code),
        fixture.id,
      ).toEqual(fixture.expectedEntryCodes);
      expect(result.report.containsDataStatements, fixture.id).toBe(false);

      if (fixture.expectedOverallStatus === "ERROR") {
        expect(result.ok, fixture.id).toBe(false);
        expect(result.candidate, fixture.id).toBeNull();
        expect(result.report.generatedSqlHash, fixture.id).toBeNull();
        expect(result.report.semanticVerification.status, fixture.id).toBe("NOT_RUN");
        continue;
      }

      expect(result.ok, fixture.id).toBe(true);
      if (!result.ok) continue;
      expect(result.candidate.sql, fixture.id).toMatch(
        new RegExp(`^${escapeRegExp(EXPORT_HEADER)}`),
      );
      expect(result.candidate.sqlHash, fixture.id).toBe(fixture.expectedGeneratedSqlHash);
      expect(result.report.generatedSqlHash, fixture.id).toBe(fixture.expectedGeneratedSqlHash);
      expect(result.report.semanticVerification, fixture.id).toMatchObject({
        status: "VERIFIED",
        sourceExportableHash: fixture.expectedExportableSchemaHash,
        generatedExportableHash: fixture.expectedExportableSchemaHash,
        changes: [],
      });
      expect(result.report.acknowledgementRequired, fixture.id).toBe(
        fixture.expectedOverallStatus === "PARTIAL" ||
          fixture.expectedOverallStatus === "UNSUPPORTED",
      );

      const analysis = analyzeSqlSource(result.candidate.sql, "/generated.sql", fixture.dialect);
      expect(
        analysis.statements.filter(({ kind }) => kind === "DML" || kind === "COPY"),
        fixture.id,
      ).toEqual([]);
      expect(JSON.parse(JSON.stringify(result)), fixture.id).toEqual(result);
      expect(structuredClone(result), fixture.id).toEqual(result);
    }
  });

  it("exports every successful SQL capability candidate back through the same dialect", async () => {
    for (const fixture of sqlCapabilityFixtures) {
      const imported = await convertSqlImport({
        dialect: fixture.dialect,
        source: fixture.source,
        filepath: `/sql-capabilities/${fixture.id}.sql`,
      });
      if (!imported.ok) continue;

      const exported = await convertDbmlToSqlExport({
        primaryDialect: fixture.dialect,
        targetDialect: fixture.dialect,
        source: imported.candidate.dbml,
        filepath: `/sql-capabilities/${fixture.id}.dbml`,
      });
      expect(exported.ok, fixture.id).toBe(true);
      expect(exported.report.semanticVerification.status, fixture.id).toBe("VERIFIED");
      expect(exported.report.containsDataStatements, fixture.id).toBe(false);
    }
  });

  it("keeps physical FK direction, ordered composite columns, and actions", async () => {
    const source = `Table app.parents {
  tenant_id bigint [not null]
  id bigint [not null]
  indexes { (tenant_id, id) [pk] }
}

Table app.children {
  tenant_id bigint [not null]
  parent_id bigint
  reverse_id bigint
}

Ref forward: app.children.(tenant_id, parent_id) > app.parents.(tenant_id, id) [delete: cascade, update: no action]
Ref reverse: app.parents.id < app.children.reverse_id [delete: restrict]
`;

    const result = await convertDbmlToSqlExport({
      primaryDialect: "POSTGRESQL",
      targetDialect: "POSTGRESQL",
      source,
    });
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.candidate.sql).toContain(
      'FOREIGN KEY ("tenant_id", "parent_id") REFERENCES "app"."parents" ("tenant_id", "id")',
    );
    expect(result.candidate.sql).toContain("ON DELETE CASCADE ON UPDATE NO ACTION");
    expect(result.candidate.sql).toContain(
      'FOREIGN KEY ("reverse_id") REFERENCES "app"."parents" ("id")',
    );
    expect(result.report.semanticVerification.status).toBe("VERIFIED");
  });

  it("verifies composite junction tables and fails closed on junction name collisions", async () => {
    const composite = await convertDbmlToSqlExport({
      primaryDialect: "POSTGRESQL",
      targetDialect: "POSTGRESQL",
      source: `Table app.left_items {
  tenant_id bigint
  id bigint
  indexes { (tenant_id, id) [pk] }
}

Table app.right_items {
  tenant_id bigint
  id bigint
  indexes { (tenant_id, id) [pk] }
}

Ref item_links: app.left_items.(tenant_id, id) <> app.right_items.(tenant_id, id)
`,
    });
    expect(composite.ok).toBe(true);
    expect(composite.report.semanticVerification.status).toBe("VERIFIED");
    if (composite.ok) {
      expect(composite.candidate.sql).toContain(
        'PRIMARY KEY ("left_items_tenant_id", "left_items_id", "right_items_tenant_id", "right_items_id")',
      );
    }

    const collision = await convertDbmlToSqlExport({
      primaryDialect: "POSTGRESQL",
      targetDialect: "POSTGRESQL",
      source: `Table app.authors { id bigint [pk] }
Table app.books { id bigint [pk] }
Table app.authors_books { id bigint [pk] }
Ref author_books: app.authors.id <> app.books.id
`,
    });
    expect(collision).toMatchObject({
      ok: false,
      candidate: null,
      report: {
        diagnostics: [
          {
            code: "SQL_EXPORT_JUNCTION_TABLE_NAME_COLLISION",
            severity: "ERROR",
          },
        ],
      },
    });

    const lossyActions = await convertDbmlToSqlExport({
      primaryDialect: "POSTGRESQL",
      targetDialect: "POSTGRESQL",
      source: `Table app.authors { id bigint [pk] }
Table app.books { id bigint [pk] }
Ref author_books: app.authors.id <> app.books.id [delete: cascade, update: restrict]
`,
    });
    expect(lossyActions.ok).toBe(false);
    expect(lossyActions.report.diagnostics[0]?.code).toBe("SQL_EXPORT_INTERNAL_SEMANTIC_MISMATCH");

    const sameEndpoint = await convertDbmlToSqlExport({
      primaryDialect: "POSTGRESQL",
      targetDialect: "POSTGRESQL",
      source: `Table app.people { id bigint [pk] }
Ref friendships: app.people.id <> app.people.id
`,
    });
    expect(sameEndpoint.ok).toBe(false);
    expect(sameEndpoint.report.diagnostics[0]?.code).toBe("DBML_SEMANTIC_SAME_ENDPOINT");
  });

  it("rejects an incomplete physical junction during semantic verification", async () => {
    const source = await parseDbmlV2(`Table app.authors { id bigint [pk] }
Table app.books { id bigint [pk] }
Ref author_books: app.authors.id <> app.books.id
`);
    const incomplete = await parseDbmlV2(`Table app.authors { id bigint [pk] }
Table app.books { id bigint [pk] }
Table app.authors_books {
  authors_id bigint
  books_id bigint
}
Ref: app.authors_books.authors_id > app.authors.id
Ref: app.authors_books.books_id > app.books.id
`);
    expect(source.ok && incomplete.ok).toBe(true);
    if (!source.ok || !incomplete.ok) return;

    const verification = await verifyExportableSchemaGraphs(
      source.graph,
      incomplete.graph,
      "POSTGRESQL",
    );
    expect(verification.status).toBe("FAILED");
    expect(verification.changes).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ operation: "ADD", elementKind: "table" }),
        expect.objectContaining({ operation: "DELETE", elementKind: "reference" }),
      ]),
    );
  });

  it("removes inactive references and records only from the ephemeral export model", async () => {
    const rowSentinel = `private-row-${"x".repeat(256 * 1024)}`;
    const source = `Table parents {
  id bigint [pk]
}

Table children {
  id bigint [pk]
  parent_id bigint
  payload text

  Records {
    1, 1, '${rowSentinel}'
  }
}

Ref active_parent: children.parent_id > parents.id
Ref inactive_parent: children.id - parents.id [inactive]
`;
    const before = await parseDbmlV2(source);
    expect(before.ok).toBe(true);

    const result = await convertDbmlToSqlExport({
      primaryDialect: "POSTGRESQL",
      targetDialect: "POSTGRESQL",
      source,
    });
    expect(result.ok).toBe(true);
    if (!result.ok || !before.ok) return;

    expect(result.candidate.sql).not.toContain("INSERT");
    expect(result.candidate.sql).not.toContain("COPY");
    expect(result.candidate.sql).not.toContain(rowSentinel);
    expect(result.candidate.sql).not.toContain("inactive_parent");
    expect(result.candidate.sql).toContain("active_parent");
    expect(JSON.stringify(result.report)).not.toContain(rowSentinel);

    const after = await parseDbmlV2(source);
    expect(after).toEqual(before);
    expect(after.ok && after.graph.references.some(({ inactive }) => inactive)).toBe(true);
  });

  it("blocks invalid DBML, empty filepaths, and cross-dialect targets without a candidate", async () => {
    const invalid = await convertDbmlToSqlExport({
      primaryDialect: "MYSQL",
      targetDialect: "MYSQL",
      source: "Table broken { id }",
      filepath: "custom/유니코드🚀.dbml",
    });
    expect(invalid.ok).toBe(false);
    expect(invalid.candidate).toBeNull();
    expect(invalid.report.diagnostics[0]).toMatchObject({
      severity: "ERROR",
      range: { filepath: "custom/유니코드🚀.dbml" },
    });

    const invalidFilepath = await convertDbmlToSqlExport({
      primaryDialect: "MYSQL",
      targetDialect: "MYSQL",
      source: "Table valid_table { id bigint [pk] }",
      filepath: "",
    });
    expect(invalidFilepath.ok).toBe(false);
    expect(invalidFilepath.report.diagnostics[0]?.code).toBe("DBML_PARSE_INTERNAL_FILEPATH");

    const mismatch = await convertDbmlToSqlExport({
      primaryDialect: "POSTGRESQL",
      targetDialect: "MYSQL",
      source: "this is deliberately not parsed",
    });
    expect(mismatch).toMatchObject({
      ok: false,
      candidate: null,
      report: {
        overallStatus: "ERROR",
        diagnostics: [{ code: "SQL_EXPORT_DIALECT_MISMATCH", severity: "ERROR" }],
        semanticVerification: { status: "NOT_RUN" },
      },
    });
  });

  it("reports source-ranged custom type outcomes without exposing native parser text", async () => {
    const accepted = await convertDbmlToSqlExport({
      primaryDialect: "POSTGRESQL",
      targetDialect: "POSTGRESQL",
      source: `Table app.documents {
  id bigint [pk]
  content citext
}
`,
      filepath: "custom/types.dbml",
    });
    expect(accepted.ok).toBe(true);
    expect(accepted.report.overallStatus).toBe("UNSUPPORTED");
    expect(accepted.report.entries).toContainEqual(
      expect.objectContaining({
        code: "SQL_EXPORT_UNSUPPORTED_CUSTOM_TYPE",
        status: "UNSUPPORTED",
        occurrences: [
          expect.objectContaining({
            elementKind: "column",
            range: expect.objectContaining({ filepath: "custom/types.dbml", startLine: 3 }),
          }),
        ],
      }),
    );

    const rejected = await convertDbmlToSqlExport({
      primaryDialect: "MYSQL",
      targetDialect: "MYSQL",
      source: `Table app.documents {
  id bigint [pk]
  content private_customer_type
}
`,
      filepath: "custom/types.dbml",
    });
    expect(rejected.ok).toBe(false);
    expect(rejected.report.entries).toContainEqual(
      expect.objectContaining({ code: "SQL_EXPORT_UNSUPPORTED_CUSTOM_TYPE" }),
    );
    expect(JSON.stringify(rejected.report)).not.toContain("private_customer_type");
    expect(JSON.stringify(rejected.report)).not.toContain("no viable alternative");
  });

  it("reports persisted layout only when the caller supplies layout provenance", async () => {
    const input = {
      primaryDialect: "POSTGRESQL" as const,
      targetDialect: "POSTGRESQL" as const,
      source: "Table samples { id bigint [pk] }\n",
    };
    const withoutLayout = await convertDbmlToSqlExport(input);
    const withLayout = await convertDbmlToSqlExport({ ...input, hasPersistedLayout: true });

    expect(withoutLayout.report.entries.map(({ code }) => code)).not.toContain(
      "SQL_EXPORT_OMITS_LAYOUT",
    );
    expect(withLayout.report.entries).toContainEqual({
      code: "SQL_EXPORT_OMITS_LAYOUT",
      status: "PARTIAL",
      message: "Persisted diagram layout is not represented in SQL DDL.",
      occurrences: [{ elementKind: "layout", elementKey: null, range: null }],
    });
    expect(withLayout.ok && withoutLayout.ok).toBe(true);
    if (!withLayout.ok || !withoutLayout.ok) return;
    expect(withLayout.candidate).toEqual(withoutLayout.candidate);
  });

  it("fails closed when generated physical semantics are unexpectedly changed", async () => {
    const source = `Table samples {
  id bigint [pk]
  label varchar(80) [not null]
}
`;
    const parsed = await parseDbmlV2(source);
    expect(parsed.ok).toBe(true);
    if (!parsed.ok) return;

    const mutated = structuredClone(parsed.graph);
    const label = mutated.tables[0]?.columns.find(({ name }) => name === "label");
    if (!label) throw new Error("Missing label fixture column.");
    label.notNull = false;

    const verification = await verifyExportableSchemaGraphs(parsed.graph, mutated, "POSTGRESQL");
    expect(verification.status).toBe("FAILED");
    expect(verification.changes).toContainEqual(
      expect.objectContaining({
        operation: "UPDATE",
        elementKind: "column",
        changedFields: ["notNull"],
      }),
    );
  });

  it("exports the full synthetic fidelity fixture in both dialects without silent loss", async () => {
    const source = generateFidelityFixture();

    for (const dialect of ["POSTGRESQL", "MYSQL"] as const) {
      const result = await convertDbmlToSqlExport({
        primaryDialect: dialect,
        targetDialect: dialect,
        source,
        filepath: `/fidelity/${dialect.toLowerCase()}.dbml`,
        hasPersistedLayout: true,
      });
      expect(result.ok, dialect).toBe(true);
      expect(result.report.semanticVerification.status, dialect).toBe("VERIFIED");
      expect(result.report.containsDataStatements, dialect).toBe(false);
      expect(result.report.entries.length, dialect).toBeGreaterThan(0);
    }
  }, 120_000);

  it("is deterministic across repeated conversion and preserves UTF-16 source ranges", async () => {
    const source = `Project "내보내기 🚀" {
  database_type: 'PostgreSQL'
  Note: '프로젝트'
}

Table "앱 🚀"."사용자" [owner: '테스트'] {
  "식별자 🚀" bigint [pk]
}
`;
    const input = {
      primaryDialect: "POSTGRESQL" as const,
      targetDialect: "POSTGRESQL" as const,
      source,
      filepath: "relative/스키마🚀.dbml",
    };
    const first = await convertDbmlToSqlExport(input);
    const second = await convertDbmlToSqlExport(input);

    expect(second).toEqual(first);
    expect(first.report.sourceHash).toBe(await sha256Utf8(source));
    expect(first.report.parserInputHash).toBe(first.report.sourceHash);
    expect(first.report.entries.flatMap(({ occurrences }) => occurrences)).toContainEqual(
      expect.objectContaining({
        range: expect.objectContaining({
          filepath: "relative/스키마🚀.dbml",
          startLine: 1,
          startColumn: 1,
        }),
      }),
    );
  });
});

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}
