import type { PrimaryDialect } from "@er-diagram/contracts";

const POSTGRESQL_BUILTIN_TYPES = [
  "bigint",
  "bigserial",
  "bit",
  "bit varying",
  "bool",
  "boolean",
  "box",
  "bytea",
  "char",
  "character",
  "character varying",
  "cidr",
  "circle",
  "date",
  "daterange",
  "decimal",
  "double precision",
  "inet",
  "int",
  "int2",
  "int4",
  "int4range",
  "int8",
  "int8range",
  "integer",
  "interval",
  "json",
  "jsonb",
  "line",
  "lseg",
  "macaddr",
  "macaddr8",
  "money",
  "numeric",
  "numrange",
  "oid",
  "path",
  "pg_lsn",
  "point",
  "polygon",
  "real",
  "serial",
  "smallint",
  "smallserial",
  "text",
  "time",
  "time with time zone",
  "timestamp",
  "timestamp with time zone",
  "timestamp without time zone",
  "tsquery",
  "tsrange",
  "tstzrange",
  "tsvector",
  "txid_snapshot",
  "uuid",
  "varbit",
  "varchar",
  "xml",
] as const;

const MYSQL_BUILTIN_TYPES = [
  "bigint",
  "binary",
  "bit",
  "blob",
  "bool",
  "boolean",
  "char",
  "date",
  "datetime",
  "decimal",
  "double",
  "enum",
  "float",
  "geometry",
  "geometrycollection",
  "int",
  "integer",
  "json",
  "linestring",
  "longblob",
  "longtext",
  "mediumblob",
  "mediumint",
  "mediumtext",
  "multilinestring",
  "multipoint",
  "multipolygon",
  "numeric",
  "point",
  "polygon",
  "real",
  "serial",
  "set",
  "smallint",
  "text",
  "time",
  "timestamp",
  "tinyblob",
  "tinyint",
  "tinytext",
  "varbinary",
  "varchar",
  "year",
] as const;

const TYPE_CATALOGS: Readonly<Record<PrimaryDialect, readonly string[]>> = {
  POSTGRESQL: POSTGRESQL_BUILTIN_TYPES,
  MYSQL: MYSQL_BUILTIN_TYPES,
};

const TYPE_CATALOG_SETS: Readonly<Record<PrimaryDialect, ReadonlySet<string>>> = {
  POSTGRESQL: new Set(POSTGRESQL_BUILTIN_TYPES),
  MYSQL: new Set(MYSQL_BUILTIN_TYPES),
};

export function getSqlBuiltinTypes(dialect: PrimaryDialect): readonly string[] {
  return [...TYPE_CATALOGS[dialect]];
}

export function isSqlBuiltinType(dialect: PrimaryDialect, typeName: string): boolean {
  return TYPE_CATALOG_SETS[dialect].has(typeName);
}
