import { ModelExporter, Parser, type Database } from "@dbml/core";
import type { Diagnostic, PrimaryDialect, SourceRange } from "@er-diagram/contracts";
import { parseDbmlV2ForAdapter, type DbmlAdapterParseResult } from "./dbml-parser-adapter.js";
import { isSourceRangeValid, resolvePublicFilepath } from "./dbml-source-range.js";
import { sha256Utf8 } from "./hash.js";
import {
  DBML_PARSER_VERSION,
  type ColumnNode,
  type SchemaElementKey,
  type SchemaElementKind,
  type SchemaGraph,
} from "./schema-graph.js";
import { SCHEMA_SEMANTICS_VERSION } from "./schema-semantics.js";
import type { ConversionStatus } from "./sql-capabilities.js";
import {
  notRunSqlExportSemanticVerification,
  SQL_EXPORT_SEMANTICS_VERSION,
  type SqlExportSemanticVerification,
  verifyExportableSchemaGraphs,
} from "./sql-export-semantics.js";
import { convertSqlModelToGraph } from "./sql-model-graph.js";
import { analyzeSqlSource } from "./sql-source-analyzer.js";
import { isSqlBuiltinType } from "./sql-type-catalog.js";

export { SQL_EXPORT_SEMANTICS_VERSION } from "./sql-export-semantics.js";
export type { SqlExportSemanticVerification } from "./sql-export-semantics.js";

export const SQL_EXPORT_REPORT_VERSION = 1 as const;

const DEFAULT_DBML_FILEPATH = "/main.dbml";
const GENERATED_SQL_FILEPATH = "/generated.sql";
const GENERATED_DBML_FILEPATH = "/generated.dbml";

export const SQL_EXPORT_HEADER = `-- Generated by DBML·SQL ERD Studio as empty-schema create DDL.
-- This is not a migration. Review before applying to an existing database.`;

const STATUS_RANK: Readonly<Record<ConversionStatus, number>> = {
  EXACT: 0,
  NORMALIZED: 1,
  PARTIAL: 2,
  UNSUPPORTED: 3,
  ERROR: 4,
};

export interface SqlExportConversionInput {
  readonly primaryDialect: PrimaryDialect;
  readonly targetDialect: PrimaryDialect;
  readonly source: string;
  readonly filepath?: string;
  readonly hasPersistedLayout?: boolean;
}

export type SqlExportOccurrenceKind = SchemaElementKind | "record" | "layout";

export interface SqlExportOccurrence {
  readonly elementKind: SqlExportOccurrenceKind;
  readonly elementKey: SchemaElementKey | null;
  readonly range: SourceRange | null;
}

export interface SqlExportReportEntry {
  readonly code: string;
  readonly status: Exclude<ConversionStatus, "EXACT">;
  readonly message: string;
  readonly occurrences: SqlExportOccurrence[];
}

export interface SqlExportReport {
  readonly reportVersion: typeof SQL_EXPORT_REPORT_VERSION;
  readonly exportSemanticsVersion: typeof SQL_EXPORT_SEMANTICS_VERSION;
  readonly sourceFilepath: string;
  readonly sourceHash: string;
  readonly parserInputHash: string;
  readonly primaryDialect: PrimaryDialect;
  readonly targetDialect: PrimaryDialect;
  readonly parserVersions: {
    readonly dbmlCore: typeof DBML_PARSER_VERSION;
    readonly dbmlParse: typeof DBML_PARSER_VERSION;
  };
  readonly schemaSemanticsVersion: typeof SCHEMA_SEMANTICS_VERSION;
  readonly ddlKind: "EMPTY_SCHEMA_CREATE";
  readonly overallStatus: ConversionStatus;
  readonly acknowledgementRequired: boolean;
  readonly generatedSqlHash: string | null;
  readonly containsDataStatements: boolean;
  readonly entries: SqlExportReportEntry[];
  readonly diagnostics: Diagnostic[];
  readonly semanticVerification: SqlExportSemanticVerification;
}

export type SqlExportConversionResult =
  | {
      readonly ok: true;
      readonly report: SqlExportReport;
      readonly candidate: {
        readonly sql: string;
        readonly sqlHash: string;
      };
    }
  | {
      readonly ok: false;
      readonly report: SqlExportReport;
      readonly candidate: null;
    };

interface EntryDefinition {
  readonly status: SqlExportReportEntry["status"];
  readonly message: string;
}

type NormalizedModel = ReturnType<Database["normalize"]>;

interface TokenLike {
  readonly start: {
    readonly offset: number;
    readonly line: number;
    readonly column: number;
  };
  readonly end: {
    readonly offset: number;
    readonly line: number;
    readonly column: number;
  };
  readonly filepath?: string | { readonly absolute?: string; readonly path?: string };
}

class SqlExportInternalError extends Error {
  constructor(
    readonly code: string,
    message: string,
    readonly range?: SourceRange,
  ) {
    super(message);
    this.name = "SqlExportInternalError";
  }
}

const ENTRY_DEFINITIONS: Readonly<Record<string, EntryDefinition>> = {
  SQL_EXPORT_MATERIALIZES_TABLE_PARTIAL: {
    status: "NORMALIZED",
    message: "TablePartial members are materialized into physical table definitions.",
  },
  SQL_EXPORT_NORMALIZES_MANY_TO_MANY: {
    status: "NORMALIZED",
    message: "Many-to-many relationships are represented by generated junction tables.",
  },
  SQL_EXPORT_NORMALIZES_MYSQL_ENUM: {
    status: "NORMALIZED",
    message: "DBML enum declarations are represented as MySQL column enum constraints.",
  },
  SQL_EXPORT_NORMALIZES_SQL_SYNTAX: {
    status: "NORMALIZED",
    message: "Equivalent type, expression, or generated constraint syntax is normalized in SQL.",
  },
  SQL_EXPORT_NORMALIZES_TABLE_ALIAS: {
    status: "NORMALIZED",
    message: "DBML table aliases are not part of physical SQL schema definitions.",
  },
  SQL_EXPORT_OMITS_DIAGRAM_VIEW: {
    status: "PARTIAL",
    message: "DiagramView definitions are not represented in SQL DDL.",
  },
  SQL_EXPORT_OMITS_ENRICHMENT: {
    status: "PARTIAL",
    message: "DBML visualization metadata and non-SQL notes are not represented in SQL DDL.",
  },
  SQL_EXPORT_OMITS_INACTIVE_REFERENCE: {
    status: "PARTIAL",
    message: "Inactive visualization relationships are omitted from SQL foreign keys.",
  },
  SQL_EXPORT_OMITS_LAYOUT: {
    status: "PARTIAL",
    message: "Persisted diagram layout is not represented in SQL DDL.",
  },
  SQL_EXPORT_OMITS_PROJECT: {
    status: "PARTIAL",
    message: "DBML Project metadata is not represented in SQL DDL.",
  },
  SQL_EXPORT_OMITS_RECORDS: {
    status: "PARTIAL",
    message: "DBML Records are intentionally omitted from empty-schema create DDL.",
  },
  SQL_EXPORT_OMITS_STICKY_NOTE: {
    status: "PARTIAL",
    message: "DBML sticky notes are not represented in SQL DDL.",
  },
  SQL_EXPORT_OMITS_TABLE_GROUP: {
    status: "PARTIAL",
    message: "TableGroup definitions are not represented in SQL DDL.",
  },
  SQL_EXPORT_PARTIAL_CARDINALITY: {
    status: "PARTIAL",
    message:
      "One-to-one or required/optional relationship cardinality is not fully encoded by SQL foreign keys.",
  },
  SQL_EXPORT_PARTIAL_MYSQL_TABLE_COMMENT: {
    status: "PARTIAL",
    message: "Pinned MySQL parsing cannot semantically re-verify exported table comments.",
  },
  SQL_EXPORT_PARTIAL_POSTGRESQL_ENUM_ARRAY: {
    status: "PARTIAL",
    message: "Pinned PostgreSQL export has a known schema-qualified enum array projection gap.",
  },
  SQL_EXPORT_UNSUPPORTED_CUSTOM_TYPE: {
    status: "UNSUPPORTED",
    message: "A custom or extension type is outside the verified built-in type catalog.",
  },
};

export async function convertDbmlToSqlExport(
  input: SqlExportConversionInput,
): Promise<SqlExportConversionResult> {
  const filepath = input.filepath ?? DEFAULT_DBML_FILEPATH;
  const sourceHash = await sha256Utf8(input.source);
  const initialReport = baseReport(input, filepath, sourceHash);

  if (input.targetDialect !== input.primaryDialect) {
    return failure(initialReport, [
      errorDiagnostic(
        "SQL_EXPORT_DIALECT_MISMATCH",
        "SQL export target must match the project primary dialect.",
      ),
    ]);
  }

  const parsed = await parseDbmlV2ForAdapter(input.source, filepath);
  if (!parsed.ok) {
    return failure(initialReport, redactDbmlDiagnostics(parsed.diagnostics));
  }

  let entries: SqlExportReportEntry[];
  try {
    entries = collectReportEntries(parsed, input.primaryDialect, input.hasPersistedLayout ?? false);
  } catch (error) {
    const internal = asInternalError(error);
    return failure(initialReport, [
      errorDiagnostic(internal.code, internal.message, internal.range),
    ]);
  }

  let sanitized: NormalizedModel;
  try {
    sanitized = sanitizedExportModel(parsed.database);
  } catch {
    return failure({ ...initialReport, entries }, [
      errorDiagnostic(
        "SQL_EXPORT_INTERNAL_MODEL_SANITIZATION",
        "DBML schema model could not be prepared for record-free SQL export.",
      ),
    ]);
  }

  let generatedSql: string;
  try {
    const ddl = ModelExporter.export(sanitized, parserFormat(input.primaryDialect));
    generatedSql = addEmptySchemaHeader(ddl);
  } catch {
    return failure({ ...initialReport, entries }, [
      errorDiagnostic(
        "SQL_EXPORT_INTERNAL_EXPORTER_FAILURE",
        "DBML schema could not be exported by the pinned SQL exporter.",
      ),
    ]);
  }

  const analysis = analyzeSqlSource(generatedSql, GENERATED_SQL_FILEPATH, input.primaryDialect);
  const dataStatements = analysis.statements.filter(
    ({ kind }) => kind === "DML" || kind === "COPY",
  );
  if (dataStatements.length > 0) {
    return failure({ ...initialReport, entries, containsDataStatements: true }, [
      errorDiagnostic(
        "SQL_EXPORT_INTERNAL_DATA_STATEMENT",
        "Generated empty-schema DDL unexpectedly contains a data statement.",
      ),
    ]);
  }

  let generatedDatabase: Database;
  try {
    generatedDatabase = Parser.parse(generatedSql, parserFormat(input.primaryDialect));
  } catch {
    const customRange = entries
      .find(({ code }) => code === "SQL_EXPORT_UNSUPPORTED_CUSTOM_TYPE")
      ?.occurrences.find(({ range }) => range !== null)?.range;
    return failure({ ...initialReport, entries }, [
      errorDiagnostic(
        "SQL_EXPORT_GENERATED_SQL_PARSE_FAILED",
        "Generated SQL could not be reparsed by the pinned same-dialect parser.",
        customRange ?? undefined,
      ),
    ]);
  }

  const hasKnownPostgresqlEnumArrayGap =
    input.primaryDialect === "POSTGRESQL" &&
    entries.some(({ code }) => code === "SQL_EXPORT_PARTIAL_POSTGRESQL_ENUM_ARRAY");
  const generatedGraph = await convertSqlModelToGraph(
    generatedDatabase,
    GENERATED_DBML_FILEPATH,
    hasKnownPostgresqlEnumArrayGap
      ? { normalizedModel: repairPostgresqlEnumArrayModel(generatedDatabase, parsed.graph) }
      : {},
  );
  if (
    !generatedGraph.ok ||
    (generatedGraph.semanticVerification.status !== "VERIFIED" && !hasKnownPostgresqlEnumArrayGap)
  ) {
    return failure({ ...initialReport, entries }, [
      errorDiagnostic(
        "SQL_EXPORT_INTERNAL_GENERATED_MODEL",
        "Reparsed SQL could not be converted into a verified physical schema model.",
      ),
    ]);
  }
  if (hasJunctionTableNameCollision(parsed.graph, generatedGraph.graph)) {
    return failure({ ...initialReport, entries }, [
      errorDiagnostic(
        "SQL_EXPORT_JUNCTION_TABLE_NAME_COLLISION",
        "A generated many-to-many junction table collides with an existing table name.",
      ),
    ]);
  }

  const semanticVerification = await verifyExportableSchemaGraphs(
    parsed.graph,
    generatedGraph.graph,
    input.primaryDialect,
  );
  if (semanticVerification.status !== "VERIFIED") {
    return failure({ ...initialReport, entries, semanticVerification }, [
      errorDiagnostic(
        "SQL_EXPORT_INTERNAL_SEMANTIC_MISMATCH",
        "Generated SQL does not match the exportable DBML schema semantics.",
      ),
    ]);
  }

  const generatedSqlHash = await sha256Utf8(generatedSql);
  const overallStatus = maxStatus(entries.map(({ status }) => status));
  const report: SqlExportReport = {
    ...initialReport,
    overallStatus,
    acknowledgementRequired: overallStatus === "PARTIAL" || overallStatus === "UNSUPPORTED",
    generatedSqlHash,
    entries,
    diagnostics: redactDbmlDiagnostics(parsed.graph.diagnostics),
    semanticVerification,
  };
  return {
    ok: true,
    report,
    candidate: { sql: generatedSql, sqlHash: generatedSqlHash },
  };
}

function baseReport(
  input: SqlExportConversionInput,
  sourceFilepath: string,
  sourceHash: string,
): SqlExportReport {
  return {
    reportVersion: SQL_EXPORT_REPORT_VERSION,
    exportSemanticsVersion: SQL_EXPORT_SEMANTICS_VERSION,
    sourceFilepath,
    sourceHash,
    parserInputHash: sourceHash,
    primaryDialect: input.primaryDialect,
    targetDialect: input.targetDialect,
    parserVersions: {
      dbmlCore: DBML_PARSER_VERSION,
      dbmlParse: DBML_PARSER_VERSION,
    },
    schemaSemanticsVersion: SCHEMA_SEMANTICS_VERSION,
    ddlKind: "EMPTY_SCHEMA_CREATE",
    overallStatus: "ERROR",
    acknowledgementRequired: false,
    generatedSqlHash: null,
    containsDataStatements: false,
    entries: [],
    diagnostics: [],
    semanticVerification: notRunSqlExportSemanticVerification(),
  };
}

function failure(report: SqlExportReport, diagnostics: Diagnostic[]): SqlExportConversionResult {
  return {
    ok: false,
    report: {
      ...report,
      overallStatus: "ERROR",
      acknowledgementRequired: false,
      generatedSqlHash: null,
      diagnostics,
    },
    candidate: null,
  };
}

function collectReportEntries(
  parsed: Extract<DbmlAdapterParseResult, { ok: true }>,
  dialect: PrimaryDialect,
  hasPersistedLayout: boolean,
): SqlExportReportEntry[] {
  const occurrences = new Map<string, SqlExportOccurrence[]>();
  const add = (code: string, values: readonly SqlExportOccurrence[]): void => {
    const current = occurrences.get(code) ?? [];
    current.push(...values);
    occurrences.set(code, current);
  };
  const graph = parsed.graph;

  add(
    "SQL_EXPORT_NORMALIZES_TABLE_ALIAS",
    graph.tables
      .filter(({ alias }) => alias !== null)
      .map((table) => nodeOccurrence("table", table)),
  );
  add(
    "SQL_EXPORT_MATERIALIZES_TABLE_PARTIAL",
    graph.partials.map((partial) => nodeOccurrence("partial", partial)),
  );
  if (dialect === "MYSQL") {
    add(
      "SQL_EXPORT_NORMALIZES_MYSQL_ENUM",
      graph.enums.map((dbEnum) => nodeOccurrence("enum", dbEnum)),
    );
  }
  add(
    "SQL_EXPORT_NORMALIZES_MANY_TO_MANY",
    graph.references
      .filter(isManyToMany)
      .map((reference) => nodeOccurrence("reference", reference)),
  );
  add("SQL_EXPORT_NORMALIZES_SQL_SYNTAX", normalizedSyntaxOccurrences(graph, dialect));
  add("SQL_EXPORT_OMITS_PROJECT", graph.project ? [nodeOccurrence("project", graph.project)] : []);
  add(
    "SQL_EXPORT_OMITS_STICKY_NOTE",
    graph.notes.map((note) => nodeOccurrence("note", note)),
  );
  add(
    "SQL_EXPORT_OMITS_TABLE_GROUP",
    graph.groups.map((group) => nodeOccurrence("group", group)),
  );
  add(
    "SQL_EXPORT_OMITS_DIAGRAM_VIEW",
    graph.views.map((view) => nodeOccurrence("view", view)),
  );
  add("SQL_EXPORT_OMITS_ENRICHMENT", enrichmentOccurrences(graph));
  add(
    "SQL_EXPORT_OMITS_INACTIVE_REFERENCE",
    graph.references
      .filter(({ inactive }) => inactive)
      .map((reference) => nodeOccurrence("reference", reference)),
  );
  add(
    "SQL_EXPORT_PARTIAL_CARDINALITY",
    graph.references
      .filter((reference) => !reference.inactive && hasLossyCardinality(reference))
      .map((reference) => nodeOccurrence("reference", reference)),
  );
  add(
    "SQL_EXPORT_PARTIAL_POSTGRESQL_ENUM_ARRAY",
    dialect === "POSTGRESQL" ? postgresEnumArrayOccurrences(graph) : [],
  );
  add(
    "SQL_EXPORT_PARTIAL_MYSQL_TABLE_COMMENT",
    dialect === "MYSQL"
      ? graph.tables
          .filter(({ note }) => note !== null)
          .map((table) => nodeOccurrence("table", table))
      : [],
  );
  add("SQL_EXPORT_UNSUPPORTED_CUSTOM_TYPE", customTypeOccurrences(graph, dialect));

  const records = parsed.database.records as unknown as Array<{ token?: TokenLike }>;
  add(
    "SQL_EXPORT_OMITS_RECORDS",
    records.map(({ token }) => ({
      elementKind: "record" as const,
      elementKey: null,
      range: recordRange(token, parsed.sourceContext),
    })),
  );
  if (hasPersistedLayout) {
    add("SQL_EXPORT_OMITS_LAYOUT", [{ elementKind: "layout", elementKey: null, range: null }]);
  }

  return [...occurrences]
    .filter(([, values]) => values.length > 0)
    .map(([code, values]) => {
      const definition = ENTRY_DEFINITIONS[code];
      if (!definition) {
        throw new SqlExportInternalError(
          "SQL_EXPORT_INTERNAL_REPORT_RULE",
          "SQL export report rule is not registered.",
        );
      }
      return {
        code,
        status: definition.status,
        message: definition.message,
        occurrences: deduplicateOccurrences(values).sort(compareOccurrences),
      };
    })
    .sort((left, right) => compareCodeUnits(left.code, right.code));
}

function normalizedSyntaxOccurrences(
  graph: SchemaGraph,
  dialect: PrimaryDialect,
): SqlExportOccurrence[] {
  const occurrences: SqlExportOccurrence[] = [];
  for (const table of graph.tables) {
    for (const column of table.columns) {
      const type = baseTypeName(column);
      if (
        (dialect === "POSTGRESQL" &&
          (column.increment || ["serial", "smallserial", "bigserial"].includes(type))) ||
        (dialect === "MYSQL" &&
          ["binary", "char", "varchar"].includes(type) &&
          column.type.arguments === null) ||
        hasBuiltinTypeCaseNormalization(column, dialect)
      ) {
        occurrences.push(nodeOccurrence("column", column));
      }
    }
    for (const index of table.indexes) {
      if (index.terms.some(({ kind }) => kind === "EXPRESSION")) {
        occurrences.push(nodeOccurrence("index", index));
      }
    }
  }
  return occurrences;
}

function hasJunctionTableNameCollision(
  sourceGraph: SchemaGraph,
  generatedGraph: SchemaGraph,
): boolean {
  if (!sourceGraph.references.some(isManyToMany)) return false;
  const sourceTableKeys = new Set(sourceGraph.tables.map(({ key }) => key));
  const sourceNames = new Set(
    sourceGraph.tables.map(({ schemaName, name }) => tableIdentity(schemaName, name)),
  );
  return generatedGraph.tables.some((table) => {
    if (sourceTableKeys.has(table.key)) return false;
    const match = /^(.*)\([1-9][0-9]*\)$/u.exec(table.name);
    return Boolean(match?.[1] && sourceNames.has(tableIdentity(table.schemaName, match[1])));
  });
}

function hasBuiltinTypeCaseNormalization(column: ColumnNode, dialect: PrimaryDialect): boolean {
  const withoutArrays = stripIdentifierQuotes(column.type.name.trim().replace(/(?:\[\])+$/u, ""));
  const lowered = withoutArrays.toLowerCase();
  return withoutArrays !== lowered && isSqlBuiltinType(dialect, lowered);
}

function enrichmentOccurrences(graph: SchemaGraph): SqlExportOccurrence[] {
  const occurrences: SqlExportOccurrence[] = [];
  for (const table of graph.tables) {
    if (table.color || Object.keys(table.metadata).length > 0) {
      occurrences.push(nodeOccurrence("table", table));
    }
    for (const column of table.columns) {
      if (Object.keys(column.metadata).length > 0) {
        occurrences.push(nodeOccurrence("column", column));
      }
    }
    for (const index of table.indexes) {
      if (index.note) occurrences.push(nodeOccurrence("index", index));
    }
  }
  for (const dbEnum of graph.enums) {
    if (dbEnum.note) occurrences.push(nodeOccurrence("enum", dbEnum));
    for (const value of dbEnum.values) {
      if (value.note) occurrences.push(nodeOccurrence("enumValue", value));
    }
  }
  for (const reference of graph.references) {
    if (reference.color) occurrences.push(nodeOccurrence("reference", reference));
  }
  for (const partial of graph.partials) {
    if (partial.note || partial.color) occurrences.push(nodeOccurrence("partial", partial));
  }
  for (const group of graph.groups) {
    if (group.note || group.color || Object.keys(group.metadata).length > 0) {
      occurrences.push(nodeOccurrence("group", group));
    }
  }
  return occurrences;
}

function postgresEnumArrayOccurrences(graph: SchemaGraph): SqlExportOccurrence[] {
  const enumIdentities = new Set(
    graph.enums.map(({ schemaName, name }) => enumIdentity(schemaName, name)),
  );
  return graph.tables.flatMap((table) =>
    table.columns.flatMap((column) => {
      const name = column.type.name.trim();
      if (!name.endsWith("[]")) return [];
      return columnReferencesEnum(column, table.schemaName, enumIdentities)
        ? [nodeOccurrence("column", column)]
        : [];
    }),
  );
}

function customTypeOccurrences(graph: SchemaGraph, dialect: PrimaryDialect): SqlExportOccurrence[] {
  const enumIdentities = new Set(
    graph.enums.map(({ schemaName, name }) => enumIdentity(schemaName, name)),
  );
  return graph.tables.flatMap((table) =>
    table.columns.flatMap((column) =>
      isCustomType(column, table.schemaName, enumIdentities, dialect)
        ? [nodeOccurrence("column", column)]
        : [],
    ),
  );
}

function isCustomType(
  column: ColumnNode,
  tableSchemaName: string,
  enumIdentities: ReadonlySet<string>,
  dialect: PrimaryDialect,
): boolean {
  const rawName = column.type.name.trim();
  const withoutArrays = rawName.replace(/(?:\[\])+$/u, "");
  const name = stripIdentifierQuotes(withoutArrays).toLowerCase();
  if (columnReferencesEnum(column, tableSchemaName, enumIdentities)) {
    return false;
  }
  return !isSqlBuiltinType(dialect, name);
}

function columnReferencesEnum(
  column: ColumnNode,
  tableSchemaName: string,
  enumIdentities: ReadonlySet<string>,
): boolean {
  const rawName = stripIdentifierQuotes(column.type.name.trim().replace(/(?:\[\])+$/u, ""));
  const schemaName = stripIdentifierQuotes(column.type.schemaName ?? tableSchemaName);
  if (enumIdentities.has(enumIdentity(schemaName, rawName))) return true;

  const parts = rawName.split(".").map(stripIdentifierQuotes);
  if (parts.length < 2) return false;
  const qualifiedName = parts.at(-1);
  const qualifiedSchema = parts.at(-2);
  return Boolean(
    qualifiedName &&
      qualifiedSchema &&
      enumIdentities.has(enumIdentity(qualifiedSchema, qualifiedName)),
  );
}

function repairPostgresqlEnumArrayModel(
  database: Database,
  sourceGraph: SchemaGraph,
): NormalizedModel {
  const model = structuredClone(database.normalize());
  const sourceTableByIdentity = new Map(
    sourceGraph.tables.map((table) => [tableIdentity(table.schemaName, table.name), table]),
  );
  const enumTargets = new Map(
    sourceGraph.enums.map((dbEnum) => [
      enumIdentity(dbEnum.schemaName, dbEnum.name),
      { schemaName: dbEnum.schemaName, name: dbEnum.name },
    ]),
  );

  for (const field of Object.values(model.fields)) {
    const table = model.tables[field.tableId];
    const schema = table ? model.schemas[table.schemaId] : undefined;
    if (!table || !schema) continue;
    const sourceTable = sourceTableByIdentity.get(tableIdentity(schema.name, table.name));
    if (!sourceTable) continue;
    const sourceColumn = sourceTable.columns.find(({ name }) => name === field.name);
    if (!sourceColumn?.type.name.trim().endsWith("[]")) continue;
    const target = referencedEnumTarget(sourceColumn, sourceTable.schemaName, enumTargets);
    if (!target) continue;

    const arrayDepth = trailingArrayDepth(sourceColumn.type.name.trim());
    field.type = {
      schemaName: target.schemaName,
      type_name: `${target.name}${"[]".repeat(arrayDepth)}`,
    };
    const enumEntry = Object.values(model.enums).find((candidate) => {
      const enumSchema = model.schemas[candidate.schemaId];
      return enumSchema?.name === target.schemaName && candidate.name === target.name;
    });
    if (!enumEntry) continue;
    field.enumId = enumEntry.id;
    enumEntry.fieldIds = [...new Set([...enumEntry.fieldIds, field.id])];
  }
  return model;
}

function referencedEnumTarget(
  column: ColumnNode,
  tableSchemaName: string,
  targets: ReadonlyMap<string, { readonly schemaName: string; readonly name: string }>,
): { readonly schemaName: string; readonly name: string } | null {
  const rawName = stripIdentifierQuotes(column.type.name.trim().replace(/(?:\[\])+$/u, ""));
  const schemaName = stripIdentifierQuotes(column.type.schemaName ?? tableSchemaName);
  const direct = targets.get(enumIdentity(schemaName, rawName));
  if (direct) return direct;

  const parts = rawName.split(".").map(stripIdentifierQuotes);
  const qualifiedName = parts.at(-1);
  const qualifiedSchema = parts.at(-2);
  return qualifiedName && qualifiedSchema
    ? (targets.get(enumIdentity(qualifiedSchema, qualifiedName)) ?? null)
    : null;
}

function trailingArrayDepth(value: string): number {
  let depth = 0;
  let remaining = value;
  while (remaining.endsWith("[]")) {
    depth += 1;
    remaining = remaining.slice(0, -2);
  }
  return depth;
}

function tableIdentity(schemaName: string, tableName: string): string {
  return JSON.stringify([schemaName, tableName]);
}

function sanitizedExportModel(database: Database): NormalizedModel {
  const model = structuredClone(database.normalize());
  model.records = {};
  for (const table of Object.values(model.tables)) table.recordIds = [];

  for (const reference of Object.values(model.refs)) {
    if (!reference.inactive) continue;
    const schema = model.schemas[reference.schemaId];
    if (!schema) {
      throw new SqlExportInternalError(
        "SQL_EXPORT_INTERNAL_MODEL_SANITIZATION",
        "Inactive relationship schema ownership is invalid.",
      );
    }
    schema.refIds = schema.refIds.filter((id) => id !== reference.id);
    for (const endpointId of reference.endpointIds) {
      const endpoint = model.endpoints[endpointId];
      if (!endpoint) {
        throw new SqlExportInternalError(
          "SQL_EXPORT_INTERNAL_MODEL_SANITIZATION",
          "Inactive relationship endpoint ownership is invalid.",
        );
      }
      for (const fieldId of endpoint.fieldIds) {
        const field = model.fields[fieldId];
        if (!field) {
          throw new SqlExportInternalError(
            "SQL_EXPORT_INTERNAL_MODEL_SANITIZATION",
            "Inactive relationship field ownership is invalid.",
          );
        }
        field.endpointIds = field.endpointIds.filter((id) => id !== endpointId);
      }
      delete model.endpoints[endpointId];
    }
    delete model.refs[reference.id];
  }
  return model;
}

function addEmptySchemaHeader(ddl: string): string {
  const body = ddl.trim();
  return body.length === 0 ? `${SQL_EXPORT_HEADER}\n` : `${SQL_EXPORT_HEADER}\n\n${body}\n`;
}

function parserFormat(dialect: PrimaryDialect): "postgres" | "mysql" {
  return dialect === "POSTGRESQL" ? "postgres" : "mysql";
}

function hasLossyCardinality(reference: SchemaGraph["references"][number]): boolean {
  if (isManyToMany(reference)) return false;
  return (
    reference.endpoints.every(({ multiplicity }) => multiplicity.max === 1) ||
    reference.endpoints.some(({ multiplicity }) => multiplicity.min !== 0)
  );
}

function isManyToMany(reference: SchemaGraph["references"][number]): boolean {
  return reference.endpoints.every(({ multiplicity }) => multiplicity.max === null);
}

function baseTypeName(column: ColumnNode): string {
  return stripIdentifierQuotes(column.type.name.trim().replace(/(?:\[\])+$/u, "")).toLowerCase();
}

function nodeOccurrence(
  elementKind: SchemaElementKind,
  node: { readonly key: SchemaElementKey; readonly range: SourceRange },
): SqlExportOccurrence {
  return { elementKind, elementKey: node.key, range: node.range };
}

function recordRange(
  token: TokenLike | undefined,
  context: Extract<DbmlAdapterParseResult, { ok: true }>["sourceContext"],
): SourceRange {
  if (!token) {
    throw new SqlExportInternalError(
      "SQL_EXPORT_INTERNAL_RECORD_RANGE",
      "DBML Records source range could not be verified.",
    );
  }
  const filepath = resolvePublicFilepath(tokenFilepath(token), context);
  if (filepath === null) {
    throw new SqlExportInternalError(
      "SQL_EXPORT_INTERNAL_RECORD_RANGE",
      "DBML Records filepath could not be verified.",
    );
  }
  const range: SourceRange = {
    filepath,
    startOffset: token.start.offset,
    endOffset: token.end.offset,
    startLine: token.start.line,
    startColumn: token.start.column,
    endLine: token.end.line,
    endColumn: token.end.column,
  };
  if (!isSourceRangeValid(range, context.sourceByPublicFilepath)) {
    throw new SqlExportInternalError(
      "SQL_EXPORT_INTERNAL_RECORD_RANGE",
      "DBML Records source range could not be verified.",
    );
  }
  return range;
}

function tokenFilepath(token: TokenLike): string | null {
  if (typeof token.filepath === "string") return token.filepath;
  if (typeof token.filepath?.absolute === "string") return token.filepath.absolute;
  if (typeof token.filepath?.path === "string") return token.filepath.path;
  return null;
}

function deduplicateOccurrences(values: readonly SqlExportOccurrence[]): SqlExportOccurrence[] {
  const seen = new Set<string>();
  return values.filter((value) => {
    const identity = JSON.stringify(value);
    if (seen.has(identity)) return false;
    seen.add(identity);
    return true;
  });
}

function compareOccurrences(left: SqlExportOccurrence, right: SqlExportOccurrence): number {
  return (
    compareCodeUnits(left.range?.filepath ?? "\uffff", right.range?.filepath ?? "\uffff") ||
    (left.range?.startOffset ?? Number.MAX_SAFE_INTEGER) -
      (right.range?.startOffset ?? Number.MAX_SAFE_INTEGER) ||
    (left.range?.endOffset ?? Number.MAX_SAFE_INTEGER) -
      (right.range?.endOffset ?? Number.MAX_SAFE_INTEGER) ||
    compareCodeUnits(left.elementKey ?? "\uffff", right.elementKey ?? "\uffff") ||
    compareCodeUnits(left.elementKind, right.elementKind)
  );
}

function maxStatus(statuses: readonly ConversionStatus[]): ConversionStatus {
  return statuses.reduce<ConversionStatus>(
    (current, candidate) => (STATUS_RANK[candidate] > STATUS_RANK[current] ? candidate : current),
    "EXACT",
  );
}

function errorDiagnostic(code: string, message: string, range?: SourceRange): Diagnostic {
  return range ? { code, message, severity: "ERROR", range } : { code, message, severity: "ERROR" };
}

function redactDbmlDiagnostics(diagnostics: readonly Diagnostic[]): Diagnostic[] {
  return diagnostics
    .filter(({ code }) => code !== "DBML_SEMANTIC_INVALID_RECORDS_FIELD")
    .map((diagnostic) => ({
      code: diagnostic.code,
      message:
        diagnostic.severity === "ERROR"
          ? "DBML source is invalid and cannot be exported."
          : "DBML source validation reported non-fatal export guidance.",
      severity: diagnostic.severity,
      ...(diagnostic.range ? { range: diagnostic.range } : {}),
    }));
}

function asInternalError(error: unknown): SqlExportInternalError {
  return error instanceof SqlExportInternalError
    ? error
    : new SqlExportInternalError(
        "SQL_EXPORT_INTERNAL_REPORT_RULE",
        "SQL export report evidence could not be normalized.",
      );
}

function enumIdentity(schemaName: string, name: string): string {
  return JSON.stringify([schemaName, name]);
}

function stripIdentifierQuotes(value: string): string {
  return value.replace(/^["`]([\s\S]*)["`]$/u, "$1");
}

function compareCodeUnits(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}
