import { createHash } from "node:crypto";

import { assertNoWcagViolations } from "./accessibility-axe.js";
import { createControlledLayoutApi } from "./controlled-layout-api.js";
import { expect, type Page, test } from "./test-fixture.js";

const PROJECT_ID = "019d3f4e-7b6c-7abc-8def-9123456789ab";
const ERROR_PROJECT_ID = "019d3f4e-7b6c-7abc-8def-9123456789ac";
const REVISION_ID = "019d3f4e-7b6c-7def-9abc-9123456789ab";
const CREATED_AT = "2026-08-31T01:02:03.004Z";
const IMPORT_SQL = "CREATE TABLE users (id bigint PRIMARY KEY);\nINSERT INTO users VALUES (1);";
const IMPORT_CANDIDATE = "Table users {\n  id bigint [pk]\n}\n";
const EXPORTED_SQL = `-- Generated by DBML·SQL ERD Studio as empty-schema create DDL.
-- This is not a migration. Review before applying to an existing database.
CREATE TABLE users (id bigint PRIMARY KEY);`;
const SOURCE = `TablePartial audit_fields {
  created_at timestamp
}

Table public.users {
  id bigint [pk]
  team_id bigint
  email varchar [not null]
}

Table public.teams {
  id bigint [pk]
}

Table public.posts {
  ~audit_fields
  id bigint [pk]
}

Ref users_team: public.users.team_id > public.teams.id

TableGroup identity {
  public.users
  public.teams
}

DiagramView focus {
  Tables {
    public.users
    public.teams
  }
  TableGroups { identity }
  Schemas { public }
}
`;

test("startup loading and failure states expose a single accessible main flow", async ({
  page,
}) => {
  let releaseFirstRequest: (() => void) | undefined;
  let runtimeRequests = 0;
  await page.route("**/api/v1/runtime-config", async (route) => {
    runtimeRequests += 1;
    if (runtimeRequests > 1) {
      await route.fallback();
      return;
    }
    await new Promise<void>((resolve) => {
      releaseFirstRequest = resolve;
    });
    await route.fulfill({
      status: 500,
      contentType: "application/json",
      body: JSON.stringify({ code: "STARTUP_FAILURE" }),
    });
  });
  await installEmptyProjectList(page);
  await page.goto("/");

  await expect(page.getByRole("heading", { name: "Starting workspace" })).toBeVisible();
  await assertNoWcagViolations(page, "runtime configuration loading");
  releaseFirstRequest?.();
  await expect(
    page.getByRole("heading", { name: "Runtime configuration unavailable" }),
  ).toBeVisible();
  await assertNoWcagViolations(page, "runtime configuration error");

  await page.getByRole("button", { name: "Retry" }).click();
  await expect(page.getByRole("heading", { name: "Projects", exact: true })).toBeVisible();
});

test("project entry routes and create dialog pass the WCAG A/AA scan", async ({ page }) => {
  await installEmptyProjectList(page);
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "No projects yet" })).toBeVisible();
  await page.keyboard.press("Tab");
  await expect(page.getByRole("link", { name: "Skip to main content" })).toBeFocused();
  await assertNoWcagViolations(page, "empty Project Home");

  const createTrigger = page.getByRole("button", { name: "New project" });
  await createTrigger.click();
  const dialog = page.getByRole("dialog", { name: "Create project" });
  await expect(dialog.getByLabel("Project name")).toBeFocused();
  await assertNoWcagViolations(page, "Create project dialog");
  await page.keyboard.press("Escape");
  await expect(createTrigger).toBeFocused();

  await page.goto("/sql-import/new");
  await expect(page.getByRole("heading", { name: "Import SQL DDL" })).toBeVisible();
  await assertNoWcagViolations(page, "new SQL import editor");

  await page.goto("/project-bundles/import");
  await expect(page.getByRole("heading", { name: "Import project bundle" })).toBeVisible();
  await assertNoWcagViolations(page, "portable bundle import");

  await page.goto("/missing-page");
  const notFoundHeading = page.getByRole("heading", { name: "Page not found" });
  await expect(notFoundHeading).toBeVisible();
  await expect(page).toHaveTitle("Page not found · DBML·SQL ERD Studio");
  await assertNoWcagViolations(page, "route not found error");

  await page.route(`**/api/v1/projects/${ERROR_PROJECT_ID}`, async (route) => {
    await route.fulfill({
      status: 500,
      contentType: "application/json",
      body: JSON.stringify({
        code: "INTERNAL_SERVER_ERROR",
        message: "The project could not be loaded.",
        correlationId: "123e4567-e89b-42d3-a456-426614174000",
      }),
    });
  });
  await page.goto(`/projects/${ERROR_PROJECT_ID}`);
  await expect(page.getByRole("heading", { name: "Project could not be loaded" })).toBeVisible();
  await assertNoWcagViolations(page, "project load error");
});

test("project mutation dialogs preserve keyboard focus and pass axe", async ({ page }) => {
  await installWorkspaceApi(page);
  await page.goto("/");
  await expect(page.getByRole("article", { name: "Accessible workspace" })).toBeVisible();
  await assertNoWcagViolations(page, "Project Home list");

  for (const dialogCase of [
    { trigger: "Rename Accessible workspace", dialog: "Rename project", initial: "Project name" },
    {
      trigger: "Duplicate Accessible workspace",
      dialog: "Duplicate project",
      initial: "Project name",
    },
  ]) {
    const trigger = page.getByRole("button", { name: dialogCase.trigger });
    await trigger.click();
    const dialog = page.getByRole("dialog", { name: dialogCase.dialog });
    await expect(dialog.getByLabel(dialogCase.initial)).toBeFocused();
    await assertNoWcagViolations(page, `${dialogCase.dialog} dialog`);
    await page.keyboard.press("Escape");
    await expect(trigger).toBeFocused();
  }

  const deleteTrigger = page.getByRole("button", { name: "Delete Accessible workspace" });
  await deleteTrigger.click();
  const deleteDialog = page.getByRole("dialog", { name: "Delete Accessible workspace?" });
  await expect(deleteDialog.getByRole("button", { name: "Cancel" })).toBeFocused();
  await assertNoWcagViolations(page, "Delete project dialog");
  await page.keyboard.press("Escape");
  await expect(deleteTrigger).toBeFocused();

  const openProject = page.getByRole("link", { name: "Open Accessible workspace" });
  await openProject.focus();
  await openProject.press("Enter");
  const workspaceHeading = page.getByRole("heading", { name: "Accessible workspace", level: 1 });
  await expect(workspaceHeading).toBeFocused({ timeout: 20_000 });
  await expect(page).toHaveTitle("Accessible workspace · DBML·SQL ERD Studio");
});

test("SQL import preview exposes independent loss acknowledgements and an axe-clean report", async ({
  page,
}) => {
  await installEmptyProjectList(page);
  await page.route("**/api/v1/sql-import/preview", async (route) => {
    const body = route.request().postDataJSON() as { commandId: string; source: string };
    await route.fulfill({
      status: 200,
      headers: {
        "content-type": "application/json",
        "x-command-id": body.commandId,
        "x-correlation-id": "123e4567-e89b-42d3-a456-426614174000",
      },
      body: JSON.stringify(sqlImportPreview(body.source)),
    });
  });
  await page.goto("/sql-import/new");
  await page.getByLabel("Project name").fill("Accessible import");
  await page.getByLabel("SQL source").fill(IMPORT_SQL);
  await page.getByRole("button", { name: "Preview import" }).click();

  await expect(page.getByRole("heading", { name: "Review SQL import" })).toBeVisible();
  const apply = page.getByRole("button", { name: "Apply import" });
  await expect(apply).toBeDisabled();
  await page.getByLabel("I understand the reported schema conversion losses").check();
  await expect(apply).toBeDisabled();
  await page.getByLabel("I confirm row data statements will be excluded").check();
  await expect(apply).toBeEnabled();
  await assertNoWcagViolations(page, "SQL import preview and acknowledgements");

  await page.getByRole("button", { name: /SQL_PARTIAL_CREATE_TABLE/ }).click();
  await expect(page.getByLabel("SQL source")).toBeFocused();
});

test("SQL and bundle export confirmations are labelled and axe-clean", async ({ page }) => {
  await installWorkspaceApi(page);
  await page.route(`**/api/v1/projects/${PROJECT_ID}/sql-export`, async (route) => {
    await route.fulfill({
      status: 200,
      headers: {
        "content-type": "application/json",
        "x-correlation-id": "123e4567-e89b-42d3-a456-426614174000",
      },
      body: JSON.stringify(sqlExportResponse()),
    });
  });
  await page.goto(`/projects/${PROJECT_ID}/sql-export`);
  await expect(page.getByRole("heading", { name: "Export empty-schema create DDL" })).toBeVisible();
  await assertNoWcagViolations(page, "SQL export input");
  await page.getByRole("button", { name: "Generate SQL export" }).click();
  await expect(page.getByText("Export report ready: PARTIAL.")).toBeVisible();
  await expect(page.getByRole("button", { name: "Download SQL" })).toBeDisabled();
  await assertNoWcagViolations(page, "SQL export report and acknowledgement");

  await page.goto(`/projects/${PROJECT_ID}/bundle-export`);
  await expect(page.getByRole("heading", { name: "Export project bundle" })).toBeVisible();
  await page.getByLabel("SQL import reports").selectOption("INCLUDE_RETAINED_SQL");
  const retainedConfirmation = page.getByLabel(/retained original SQL may contain sensitive/u);
  await expect(retainedConfirmation).toBeVisible();
  await expect(page.getByRole("button", { name: "Download portable bundle" })).toBeDisabled();
  await assertNoWcagViolations(page, "portable bundle retained SQL confirmation");
});

test("valid workspace, search, inspector, and history are keyboard reachable and axe-clean", async ({
  page,
}) => {
  test.setTimeout(90_000);
  await installWorkspaceApi(page);
  await page.goto(`/projects/${PROJECT_ID}`);
  await expect(page.getByTestId("base-diagram-layout-status")).toHaveText("Diagram layout ready", {
    timeout: 20_000,
  });
  await assertNoWcagViolations(page, "valid workspace with canvas-only initial state");
  await page.getByRole("button", { name: "Source", exact: true }).click();
  await expect(page.locator('section[aria-label="DBML source editor"] .monaco-editor')).toBeVisible(
    {
      timeout: 20_000,
    },
  );
  await expect(page.locator(".react-flow__node[tabindex='0']")).toHaveCount(0);
  await expect(page.locator(".react-flow__edge[tabindex='0']")).toHaveCount(0);
  await expect(page.locator(".diagram-table__table-action[tabindex='-1']")).toHaveCount(3);
  await expect(page.locator(".diagram-table__column-action[tabindex='-1']")).toHaveCount(6);
  await assertNoWcagViolations(page, "valid workspace");

  const search = page.getByRole("combobox", { name: "Search current view" });
  await search.fill("users");
  await expect(page.getByRole("listbox", { name: "Current view search results" })).toBeVisible();
  await search.press("ArrowDown");
  await expect(search).toHaveAttribute("aria-activedescendant", /-option-0$/);
  await assertNoWcagViolations(page, "workspace search listbox");
  await search.press("Escape");
  await expect(search).toHaveValue("");

  const viewSelector = page.getByRole("combobox", { name: "Diagram view" });
  await viewSelector.focus();
  await viewSelector.press("f");
  await expect(viewSelector).not.toHaveValue("GLOBAL");
  await page.waitForTimeout(1_100);
  await viewSelector.press("g");
  await expect(viewSelector).toHaveValue("GLOBAL");
  const detailSelector = page.getByRole("combobox", { name: "Detail level" });
  await detailSelector.focus();
  await detailSelector.press("n");
  await expect(detailSelector).toHaveValue("NAME_ONLY");
  await page.waitForTimeout(1_100);
  await detailSelector.press("f");
  await expect(detailSelector).toHaveValue("FULL");
  const collapseGroup = page.getByRole("button", {
    name: "Collapse public.identity",
    exact: true,
  });
  await collapseGroup.focus();
  await collapseGroup.press("Enter");
  const expandGroup = page.getByRole("button", { name: "Expand public.identity", exact: true });
  await expect(expandGroup).toBeVisible();
  await expandGroup.press("Enter");

  await page.getByRole("button", { name: "Outline", exact: true }).click();
  const outline = page.getByRole("region", { name: "Schema outline" });
  await outline.locator("summary").filter({ hasText: "public.users" }).press("Enter");
  const tableOutlineAction = outline.getByRole("button", {
    name: "Focus public.users in diagram",
  });
  await tableOutlineAction.focus();
  await tableOutlineAction.press("Enter");
  await page.getByRole("button", { name: "Inspector", exact: true }).click();
  const toolbar = page.getByRole("toolbar", { name: "Visual schema actions" });
  const firstAction = toolbar.getByRole("button").first();
  await firstAction.focus();
  await firstAction.press("End");
  await expect(toolbar.getByRole("button").last()).toBeFocused();
  await firstAction.press("Home");
  await expect(firstAction).toBeFocused();
  await page.getByRole("button", { name: "Update table" }).click();
  const nativeUndoField = page.getByLabel("Table note");
  await nativeUndoField.focus();
  await nativeUndoField.type("local field draft");
  await nativeUndoField.press(`${process.platform === "darwin" ? "Meta" : "Control"}+z`);
  await expect(nativeUndoField).toBeFocused();
  await expect(nativeUndoField).not.toHaveValue("local field draft");
  await expect(nativeUndoField).not.toHaveValue("");
  await assertNoWcagViolations(page, "visual command form");
  await page.getByRole("button", { name: "Cancel" }).click();

  await page.getByRole("button", { name: "Create table", exact: true }).click();
  const invalidTableName = page.getByLabel("Table name");
  await invalidTableName.fill("");
  await page.getByRole("button", { name: "Apply command" }).click();
  await expect(invalidTableName).toBeFocused();
  await expect(invalidTableName).toHaveAttribute("aria-invalid", "true");
  await expect(invalidTableName).toHaveAttribute("aria-errormessage", /.+/);
  await assertNoWcagViolations(page, "visual command validation summary");
  await page.getByRole("button", { name: "Cancel" }).click();

  const relationshipAction = outline.getByRole("button", {
    name: "Focus relationship users_team in diagram",
  });
  await relationshipAction.focus();
  await relationshipAction.press("Enter");
  await expect(page.getByText("Selected relationship")).toBeVisible();
  await expect(page.getByRole("button", { name: "Update relationship" })).toBeVisible();

  const groupAction = outline.getByRole("button", {
    name: "Focus group public.identity in diagram",
  });
  await groupAction.focus();
  await groupAction.press("Enter");
  await expect(page.getByText("Selected TableGroup")).toBeVisible();
  await expect(page.getByRole("button", { name: "Update group membership" })).toBeVisible();

  await outline.locator("summary").filter({ hasText: "public.posts" }).press("Enter");
  const partialColumnAction = outline.getByRole("button", {
    name: "Focus column created_at in diagram",
  });
  await partialColumnAction.focus();
  await partialColumnAction.press("Enter");
  await expect(page.getByText("Partial audit_fields owns this element")).toBeVisible();
  await assertNoWcagViolations(page, "partial provenance source fallback");
  const partialSourceAction = page.getByRole("button", { name: "Open partial definition" });
  await partialSourceAction.focus();
  await partialSourceAction.press("Enter");
  await expect(page.getByRole("textbox", { name: "DBML source editor" })).toBeFocused();
  await page.getByRole("button", { name: "Source", exact: true }).click();

  const resetTrigger = page.getByRole("button", { name: "Reset layout" });
  await resetTrigger.click();
  const resetDialog = page.getByRole("dialog", { name: "Reset this view layout?" });
  await expect(resetDialog.getByRole("button", { name: "Cancel" })).toBeFocused();
  await assertNoWcagViolations(page, "layout reset dialog");
  await page.keyboard.press("Escape");
  await expect(resetTrigger).toBeFocused();

  const historyTrigger = page.getByRole("button", { name: "Revision history" });
  await historyTrigger.click();
  await expect(page.getByRole("dialog", { name: "Revision history" })).toBeVisible();
  await assertNoWcagViolations(page, "revision history dialog");
  await page.keyboard.press("Escape");
  await expect(historyTrigger).toBeFocused();
});

test("invalid draft keeps the last-valid diagram and exposes the recovery state accessibly", async ({
  page,
}) => {
  test.setTimeout(90_000);
  await installWorkspaceApi(page, projectState({ invalid: true }));
  await page.goto(`/projects/${PROJECT_ID}`);

  await expect(page.getByText(/Showing last-valid revision 1/)).toBeVisible({ timeout: 20_000 });
  await expect(page.getByRole("button", { name: "Source", exact: true })).toHaveAttribute(
    "aria-expanded",
    "false",
  );
  await page.getByRole("button", { name: "Source", exact: true }).click();
  await expect(page.locator('section[aria-label="DBML source editor"] .monaco-editor')).toBeVisible(
    {
      timeout: 20_000,
    },
  );
  await expect(page.getByTestId("validation-status")).toContainText("Draft invalid");
  await expect(page.getByText("Last valid revision", { exact: true }).first()).toBeVisible();
  await expect(page.getByText(/Source navigation is disabled/)).toBeVisible();
  await page.getByRole("button", { name: "Outline", exact: true }).click();
  await expect(page.locator("#workspace-outline-surface")).toContainText("public.users");
  await page.getByRole("button", { name: "Inspector", exact: true }).click();
  await expect(page.getByRole("button", { name: "Create table" })).toBeDisabled();
  await expect(page.locator("#workspace-inspector-surface")).toHaveCSS("opacity", "1");
  await assertNoWcagViolations(page, "invalid draft and last-valid diagram recovery");
});

test("source and layout conflicts expose explicit keyboard recovery dialogs", async ({ page }) => {
  test.setTimeout(90_000);
  const conflictApi = await installWorkspaceApi(page, projectState(), {
    draftWrite: "CONFLICT",
  });
  await page.goto(`/projects/${PROJECT_ID}`);
  await expect(page.getByTestId("base-diagram-layout-status")).toHaveText("Diagram layout ready", {
    timeout: 20_000,
  });

  await page.getByRole("button", { name: "Source", exact: true }).click();
  await replaceEditorSource(page, `${SOURCE}\nTable public.audit_log {\n  id bigint [pk]\n}\n`);
  await page.getByRole("button", { name: "Save now" }).click();
  await expect(page.getByTestId("persistence-status")).toContainText("Conflict");
  await assertNoWcagViolations(page, "source save conflict");
  const loadDraftTrigger = page.getByRole("button", { name: "Load server draft" });
  await loadDraftTrigger.click();
  const sourceConflictDialog = page.getByRole("dialog", { name: "Load server draft?" });
  await expect(sourceConflictDialog.getByRole("button", { name: "Cancel" })).toBeFocused();
  await assertNoWcagViolations(page, "source conflict recovery dialog");
  await page.keyboard.press("Escape");
  await expect(loadDraftTrigger).toBeFocused();
  await page.getByRole("button", { name: "Source", exact: true }).click();

  conflictApi.layouts.advanceRevision();
  await page.getByRole("combobox", { name: "Detail level" }).selectOption("NAME_ONLY");
  await expect(page.getByText("Layout conflict", { exact: true }).last()).toBeVisible({
    timeout: 10_000,
  });
  await assertNoWcagViolations(page, "layout save conflict");
  const loadLayoutTrigger = page.getByRole("button", { name: "Load server layout" });
  await loadLayoutTrigger.click();
  const layoutConflictDialog = page.getByRole("dialog", { name: "Load server layout?" });
  await expect(layoutConflictDialog.getByRole("button", { name: "Cancel" })).toBeFocused();
  await assertNoWcagViolations(page, "layout conflict recovery dialog");
});

test("dirty source navigation blocker keeps source and focuses Stay", async ({ page }) => {
  test.setTimeout(90_000);
  await installWorkspaceApi(page);
  await page.goto(`/projects/${PROJECT_ID}`);
  await expect(page.getByTestId("base-diagram-layout-status")).toHaveText("Diagram layout ready", {
    timeout: 20_000,
  });

  await page.getByRole("button", { name: "Source", exact: true }).click();
  await replaceEditorSource(page, `${SOURCE}\nTable public.local_draft {\n  id bigint [pk]\n}\n`);
  await page.getByRole("link", { name: "Back" }).click();
  const blocker = page.getByRole("dialog", { name: "Leave schema workspace?" });
  await expect(blocker.getByRole("button", { name: "Stay" })).toBeFocused();
  await expect(blocker.getByRole("button", { name: "Leave workspace" })).toBeVisible();
  await assertNoWcagViolations(page, "dirty source navigation blocker");
  await blocker.getByRole("button", { name: "Stay" }).click();
  await expect(page).toHaveURL(`/projects/${PROJECT_ID}`);
  await expect(page.getByTestId("persistence-status")).toContainText("Save error");
  await assertNoWcagViolations(page, "source save error recovery");
});

test("core controls reflow without horizontal document overflow", async ({ page }) => {
  await installEmptyProjectList(page);
  await page.setViewportSize({ width: 320, height: 720 });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "No projects yet" })).toBeVisible();
  expect(
    await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1),
  ).toBe(true);
  await assertNoWcagViolations(page, "Project Home at a 320 CSS pixel reflow width");

  await installWorkspaceApi(page);
  await page.goto(`/projects/${PROJECT_ID}`);
  await expect(page.getByTestId("base-diagram-layout-status")).toHaveText("Diagram layout ready", {
    timeout: 20_000,
  });
  await page.getByRole("button", { name: "Source", exact: true }).click();
  await expect(page.locator('section[aria-label="DBML source editor"] .monaco-editor')).toBeVisible(
    {
      timeout: 20_000,
    },
  );
  expect(
    await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1),
  ).toBe(true);
  await assertNoWcagViolations(page, "workspace controls at a 320 CSS pixel reflow width");
});

async function installEmptyProjectList(page: Page): Promise<void> {
  await page.route("**/api/v1/projects", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ projects: [] }),
    });
  });
}

async function installWorkspaceApi(
  page: Page,
  state: ReturnType<typeof projectState> = projectState(),
  options: { readonly draftWrite?: "CONFLICT" } = {},
) {
  const layouts = createControlledLayoutApi(PROJECT_ID);
  await page.route("**/api/v1/projects**", async (route) => {
    const request = route.request();
    const pathname = new URL(request.url()).pathname;
    const method = request.method();
    const command = request.postDataJSON() as Record<string, unknown> | null;
    const commandId = typeof command?.commandId === "string" ? command.commandId : undefined;
    const headers = {
      "content-type": "application/json",
      "x-correlation-id": "123e4567-e89b-42d3-a456-426614174000",
      ...(commandId ? { "x-command-id": commandId } : {}),
    };
    if (await layouts.fulfillIfMatched({ route, pathname, method, command, headers })) return;
    if (method === "GET" && pathname === "/api/v1/projects") {
      await route.fulfill({
        status: 200,
        headers,
        body: JSON.stringify({ projects: [projectSummary(state)] }),
      });
      return;
    }
    if (method === "GET" && pathname === `/api/v1/projects/${PROJECT_ID}`) {
      await route.fulfill({ status: 200, headers, body: JSON.stringify({ state }) });
      return;
    }
    if (method === "GET" && pathname === `/api/v1/projects/${PROJECT_ID}/revisions`) {
      const { source: _source, ...revisionSummary } = state.currentRevision;
      await route.fulfill({
        status: 200,
        headers,
        body: JSON.stringify({ revisions: [revisionSummary] }),
      });
      return;
    }
    if (method === "PUT" && pathname === `/api/v1/projects/${PROJECT_ID}/draft`) {
      if (options.draftWrite === "CONFLICT") {
        await route.fulfill({
          status: 409,
          headers,
          body: JSON.stringify({
            code: "PROJECT_SCHEMA_REVISION_CONFLICT",
            message: "The schema revision is stale.",
            correlationId: headers["x-correlation-id"],
            currentRevisionNo: state.project.schemaRevisionNo + 1,
          }),
        });
        return;
      }
      await route.fulfill({
        status: 500,
        headers,
        body: JSON.stringify({
          code: "INTERNAL_SERVER_ERROR",
          message: "The draft could not be saved.",
          correlationId: headers["x-correlation-id"],
        }),
      });
      return;
    }
    await route.fulfill({
      status: 404,
      headers,
      body: JSON.stringify({
        code: "PROJECT_NOT_FOUND",
        message: "Project not found.",
        correlationId: headers["x-correlation-id"],
      }),
    });
  });
  return { layouts };
}

async function replaceEditorSource(page: Page, source: string): Promise<void> {
  const modifier = process.platform === "darwin" ? "Meta" : "Control";
  const editor = page.getByRole("textbox", { name: "DBML source editor" });
  await editor.focus();
  await editor.press(`${modifier}+a`);
  await editor.evaluate((element, nextSource) => {
    const clipboardData = new DataTransfer();
    clipboardData.setData("text/plain", nextSource);
    element.dispatchEvent(
      new ClipboardEvent("paste", { bubbles: true, cancelable: true, clipboardData }),
    );
  }, source);
}

function projectState(options: { readonly invalid?: boolean } = {}) {
  const lastValidRevision = {
    id: REVISION_ID,
    projectId: PROJECT_ID,
    revisionNo: 1,
    source: SOURCE,
    sourceHash: sha256(SOURCE),
    validity: "VALID" as const,
    origin: "SOURCE_EDIT" as const,
    parserVersion: "9.1.1",
    diagnosticSummary: { errors: 0, warnings: 0, infos: 0, parserVersion: "9.1.1" },
    createdAt: CREATED_AT,
  };
  const invalidSource = `${SOURCE}\nTable broken {`;
  const currentRevision = options.invalid
    ? {
        ...lastValidRevision,
        id: "019d3f4e-7b6c-7fed-9abc-9123456789ab",
        revisionNo: 2,
        source: invalidSource,
        sourceHash: sha256(invalidSource),
        validity: "INVALID" as const,
        diagnosticSummary: { errors: 1, warnings: 0, infos: 0, parserVersion: "9.1.1" },
      }
    : lastValidRevision;
  return {
    project: {
      id: PROJECT_ID,
      name: "Accessible workspace",
      primaryDialect: "POSTGRESQL" as const,
      draftSource: currentRevision.source,
      draftHash: currentRevision.sourceHash,
      lastValidRevisionId: REVISION_ID,
      parserVersion: "9.1.1",
      schemaRevisionNo: currentRevision.revisionNo,
      layoutRevisionNo: 0,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    currentRevision,
    lastValidRevision,
  };
}

function projectSummary(state: ReturnType<typeof projectState>) {
  return {
    id: state.project.id,
    name: state.project.name,
    primaryDialect: state.project.primaryDialect,
    parserVersion: state.project.parserVersion,
    schemaRevisionNo: state.project.schemaRevisionNo,
    layoutRevisionNo: state.project.layoutRevisionNo,
    draftValidity: state.currentRevision.validity,
    diagnosticSummary: state.currentRevision.diagnosticSummary,
    createdAt: state.project.createdAt,
    updatedAt: state.project.updatedAt,
  };
}

function sqlImportPreview(source: string) {
  const sourceHash = sha256(source);
  const candidateHash = sha256(IMPORT_CANDIDATE);
  return {
    previewStatus: "PREVIEWED",
    previewHash: "c".repeat(64),
    originalSqlRetention: "DISCARD",
    report: {
      reportVersion: 1,
      dialect: "POSTGRESQL",
      sourceFilepath: "/import.sql",
      sourceHash,
      parserInputHash: sourceHash,
      parserVersions: { dbmlCore: "9.1.1", dbmlParse: "9.1.1" },
      capabilityMatrixVersion: 1,
      schemaSemanticsVersion: 1,
      overallStatus: "PARTIAL",
      applyEligible: false,
      candidateDbmlHash: candidateHash,
      statements: [
        {
          statementNo: 1,
          kind: "CREATE_TABLE",
          capabilityId: "CREATE_TABLE",
          status: "PARTIAL",
          code: "SQL_PARTIAL_CREATE_TABLE",
          message: "Some table clauses are not preserved.",
          range: sourceRange(0, 44, 1, 1, 1, 45),
          clauses: [],
        },
        {
          statementNo: 2,
          kind: "DML",
          capabilityId: "DML",
          status: "UNSUPPORTED",
          code: "SQL_UNSUPPORTED_DATA_STATEMENT",
          message: "Row data is excluded from schema import.",
          range: sourceRange(45, source.length, 2, 1, 2, 30),
          clauses: [],
        },
      ],
      diagnostics: [],
      semanticVerification: {
        status: "VERIFIED",
        sourceModelHash: candidateHash,
        candidateSchemaHash: candidateHash,
        changes: [],
      },
    },
    policy: {
      policyVersion: 1,
      dataStatementNos: [2],
      dataHandling: "CONFIRMATION_REQUIRED",
      applyReadiness: "DATA_EXCLUSION_CONFIRMATION_REQUIRED",
    },
    candidate: { dbml: IMPORT_CANDIDATE, dbmlHash: candidateHash },
  };
}

function sourceRange(
  startOffset: number,
  endOffset: number,
  startLine: number,
  startColumn: number,
  endLine: number,
  endColumn: number,
) {
  return {
    filepath: "/import.sql",
    startOffset,
    endOffset,
    startLine,
    startColumn,
    endLine,
    endColumn,
  };
}

function sqlExportResponse() {
  const sourceHash = sha256(SOURCE);
  const sqlHash = sha256(EXPORTED_SQL);
  return {
    sourceSelection: "CURRENT_DRAFT",
    revisionNo: 1,
    sourceHash,
    report: {
      reportVersion: 1,
      exportSemanticsVersion: 1,
      sourceFilepath: "/main.dbml",
      sourceHash,
      parserInputHash: sourceHash,
      primaryDialect: "POSTGRESQL",
      targetDialect: "POSTGRESQL",
      parserVersions: { dbmlCore: "9.1.1", dbmlParse: "9.1.1" },
      schemaSemanticsVersion: 1,
      ddlKind: "EMPTY_SCHEMA_CREATE",
      overallStatus: "PARTIAL",
      acknowledgementRequired: true,
      generatedSqlHash: sqlHash,
      containsDataStatements: false,
      entries: [
        {
          code: "SQL_EXPORT_OMITS_TABLE_GROUP",
          status: "PARTIAL",
          message: "TableGroup definitions are not represented in SQL DDL.",
          occurrences: [],
        },
      ],
      diagnostics: [],
      semanticVerification: {
        status: "VERIFIED",
        sourceExportableHash: sourceHash,
        generatedExportableHash: sourceHash,
        changes: [],
      },
    },
    candidate: { sql: EXPORTED_SQL, sqlHash },
  };
}

function sha256(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}
