import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { expect, type Page, test } from "./test-fixture.js";

const PROJECT_ID = "019d3f4e-7b6c-7abc-8def-0123456789ab";
const VALID_REVISION_ID = "019d3f4e-7b6c-7def-9abc-0123456789ab";
const CREATED_AT = "2026-08-29T00:00:00.000Z";
const SOURCE = `Table users { id int [pk] }
TableGroup core { users }`;
const SQL = `-- Generated by DBML·SQL ERD Studio as empty-schema create DDL.
-- This is not a migration. Review before applying to an existing database.
CREATE TABLE users (id integer PRIMARY KEY);`;

test("downloads PostgreSQL DDL only after loss acknowledgement and always downloads its report", async ({
  page,
}) => {
  const errors = collectBrowserErrors(page);
  await installExportApi(page, "POSTGRESQL", false);
  await page.goto(`/projects/${PROJECT_ID}/sql-export`);

  await page.getByRole("button", { name: "Generate SQL export" }).click();
  await expect(page.getByText("Export report ready: PARTIAL.")).toBeVisible();
  await expect(page.getByRole("button", { name: "Download SQL" })).toBeDisabled();

  const reportDownloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download report JSON" }).click();
  const reportDownload = await reportDownloadPromise;
  expect(reportDownload.suggestedFilename()).toBe(
    "E2E-schema-r1-postgresql.conversion-report.json",
  );
  const reportPath = await reportDownload.path();
  expect(JSON.parse(await readFile(reportPath as string, "utf8"))).toMatchObject({
    downloadVersion: 1,
    sourceSelection: "CURRENT_DRAFT",
    report: { overallStatus: "PARTIAL" },
  });

  await page.getByLabel(/I reviewed the partial/).check();
  const sqlDownloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download SQL" }).click();
  const sqlDownload = await sqlDownloadPromise;
  expect(sqlDownload.suggestedFilename()).toBe("E2E-schema-r1-postgresql.sql");
  expect(await readFile((await sqlDownload.path()) as string, "utf8")).toBe(SQL);
  expect(errors).toEqual([]);
});

test("requires explicit last-valid selection for an invalid MySQL project", async ({ page }) => {
  const errors = collectBrowserErrors(page);
  const calls = await installExportApi(page, "MYSQL", true);
  await page.goto(`/projects/${PROJECT_ID}/sql-export`);

  await expect(page.getByRole("button", { name: "Generate SQL export" })).toBeDisabled();
  await page.getByLabel("Export last-valid revision 1 explicitly").check();
  await page.getByRole("button", { name: "Generate SQL export" }).click();
  await expect(page.getByText("Export report ready: PARTIAL.")).toBeVisible();
  expect(calls()).toEqual([{ expectedSchemaRevisionNo: 2, sourceSelection: "LAST_VALID" }]);
  expect(errors).toEqual([]);
});

async function installExportApi(page: Page, dialect: "POSTGRESQL" | "MYSQL", invalid: boolean) {
  const requests: unknown[] = [];
  const state = projectState(dialect, invalid);
  await page.route("**/api/v1/**", async (route) => {
    const request = route.request();
    const pathname = new URL(request.url()).pathname;
    if (request.method() === "GET" && pathname === "/api/v1/runtime-config") {
      await route.fallback();
      return;
    }
    const headers = {
      "content-type": "application/json",
      "x-correlation-id": "123e4567-e89b-42d3-a456-426614174000",
    };
    if (request.method() === "GET" && pathname === `/api/v1/projects/${PROJECT_ID}`) {
      await route.fulfill({ status: 200, headers, body: JSON.stringify({ state }) });
      return;
    }
    if (request.method() === "POST" && pathname === `/api/v1/projects/${PROJECT_ID}/sql-export`) {
      requests.push(request.postDataJSON());
      await route.fulfill({
        status: 200,
        headers,
        body: JSON.stringify(exportResponse(dialect, invalid ? "LAST_VALID" : "CURRENT_DRAFT")),
      });
      return;
    }
    await route.fulfill({
      status: 404,
      headers,
      body: JSON.stringify({
        code: "PROJECT_NOT_FOUND",
        message: "Project not found.",
        correlationId: headers["x-correlation-id"],
      }),
    });
  });
  return () => requests;
}

function projectState(dialect: "POSTGRESQL" | "MYSQL", invalid: boolean) {
  const valid = revision(1, SOURCE, "VALID");
  const current = invalid ? revision(2, `${SOURCE}\nTable broken {`, "INVALID") : valid;
  return {
    project: {
      id: PROJECT_ID,
      name: "E2E / schema",
      primaryDialect: dialect,
      draftSource: current.source,
      draftHash: current.sourceHash,
      lastValidRevisionId: valid.id,
      parserVersion: "9.1.1",
      schemaRevisionNo: current.revisionNo,
      layoutRevisionNo: 1,
      createdAt: CREATED_AT,
      updatedAt: CREATED_AT,
    },
    currentRevision: current,
    lastValidRevision: valid,
  };
}

function revision(revisionNo: number, source: string, validity: "VALID" | "INVALID") {
  return {
    id: revisionNo === 1 ? VALID_REVISION_ID : "019d3f4e-7b6c-7eee-8abc-0123456789ab",
    projectId: PROJECT_ID,
    revisionNo,
    source,
    sourceHash: sha256(source),
    validity,
    origin: "SOURCE_EDIT",
    parserVersion: "9.1.1",
    diagnosticSummary: {
      errors: validity === "INVALID" ? 1 : 0,
      warnings: 0,
      infos: 0,
      parserVersion: "9.1.1",
    },
    createdAt: CREATED_AT,
  };
}

function exportResponse(
  dialect: "POSTGRESQL" | "MYSQL",
  sourceSelection: "CURRENT_DRAFT" | "LAST_VALID",
) {
  const sourceHash = sha256(SOURCE);
  const sqlHash = sha256(SQL);
  return {
    sourceSelection,
    revisionNo: 1,
    sourceHash,
    report: {
      reportVersion: 1,
      exportSemanticsVersion: 1,
      sourceFilepath: "/main.dbml",
      sourceHash,
      parserInputHash: sourceHash,
      primaryDialect: dialect,
      targetDialect: dialect,
      parserVersions: { dbmlCore: "9.1.1", dbmlParse: "9.1.1" },
      schemaSemanticsVersion: 1,
      ddlKind: "EMPTY_SCHEMA_CREATE",
      overallStatus: "PARTIAL",
      acknowledgementRequired: true,
      generatedSqlHash: sqlHash,
      containsDataStatements: false,
      entries: [
        {
          code: "SQL_EXPORT_OMITS_TABLE_GROUP",
          status: "PARTIAL",
          message: "TableGroup definitions are not represented in SQL DDL.",
          occurrences: [],
        },
      ],
      diagnostics: [],
      semanticVerification: {
        status: "VERIFIED",
        sourceExportableHash: sourceHash,
        generatedExportableHash: sourceHash,
        changes: [],
      },
    },
    candidate: { sql: SQL, sqlHash },
  };
}

function sha256(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

function collectBrowserErrors(page: Page): string[] {
  const errors: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error") errors.push(message.text());
  });
  page.on("pageerror", (error) => errors.push(error.message));
  return errors;
}
